version: '1.0'
services:
  - name: db
    type: percona
    version: 5.7
    configuration: StandAlone
    username: null
    database: null
    userPassword: null
    password: null
    ports:
      - 3306
    remoteAccess: false
    deployTo:
      - percona

  - name: pma
    type: docker
    image: phpmyadmin/phpmyadmin
    version: latest
    ports:
      - 80
    remoteAccess: false
    env:
      PMA_HOST: "{{=service('db').getMasterAlias()}}"
      PMA_PORT: "{{=service('db').getMainPort()}}"
    deployTo:
      - percona

  - name: web
    type: nginx
    version: 1.15
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: pma
    deployTo:
      - percona

hosts:
  - name: percona
    requirements:
      cores: 1
      memory: 1
